### ISSUE TITLE
ブロック破壊時にエラーが出る

### ISSUE THREAD

**Issue by ZOIChannel** [yokmama/MineAndFight#6]
ゲーム実行中にブロック（石、エメラルドどちらでも）を破壊すると次のようなエラーメッセージが出ます
```
[18:17:57] [Server thread/ERROR]: Could not pass event BlockBreakEvent to MineAndFight v1.0-SNAPSHOT
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:306) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:265) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:152) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1198) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
Caused by: java.lang.IllegalArgumentException: Cannot get data class of Modern Material
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at org.bukkit.Material.getData(Material.java:3400) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	at jp.hack.minecraft.mineandfight.logic.MineAndFightLogic.onBlockBreakEvent(MineAndFightLogic.java:43) ~[?:?]
	at jp.hack.minecraft.mineandfight.core.GameManager.onBlockBreakEvent(GameManager.java:103) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
	... 20 more
```

**Comment by ZOIChannel** [comment]
![Desktop Screenshot 2020 06 20 - 18 31 13 77](https://user-images.githubusercontent.com/51259731/85198549-656c1c80-b324-11ea-8011-91e400907449.png)
![Desktop Screenshot 2020 06 20 - 18 31 25 63](https://user-images.githubusercontent.com/51259731/85198551-68670d00-b324-11ea-857b-98429b52712a.png)

**Comment by ryosuke0818** [comment]
BlockBreakEventが渡せてないみたいです。僕には原因がさっぱりわかりません。寺園さんお願いします。
